#!/usr/bin/exec-suid --real -- /usr/bin/python -I
from os.path import exists
import sys

r1 = False
r2 = False

def prRed(skk): print("\033[91m {}\033[00m" .format(skk))
def prGreen(skk): print("\033[92m {}\033[00m" .format(skk))
def prYellow(skk): print("\033[93m {}\033[00m" .format(skk))

if len(sys.argv) != 2:
	prRed("Please supply your python file.")
	exit(0)

if not exists(sys.argv[1]):
	prRed(f"It appears the file '{sys.argv[1]}' does not exist!")
	exit(0)

with open(sys.argv[1], 'r') as fObj:
	lines = fObj.readlines()

for line in lines:
	if not r1:
		if '.choice' in line:
			r1 = True
	if not r2:
		if '.randint' in line:
			r2 = True

if not r1:
	prRed("It appears you didn't get a random item from your grocery list!")
	exit(0)
if not r2:
	prRed("It appears you didn't generate a random integer!")
	exit(0)

prGreen("Here is your flag!")
with open('/flag', 'r') as fObj:
    prGreen(fObj.read())
