#!/usr/bin/exec-suid --real -- /usr/bin/python -I
from os.path import exists
import sys

o1 = False
o2 = False
o3 = False

def prRed(skk): print("\033[91m {}\033[00m" .format(skk))
def prGreen(skk): print("\033[92m {}\033[00m" .format(skk))
def prYellow(skk): print("\033[93m {}\033[00m" .format(skk))

if len(sys.argv) != 2:
	prRed("Please supply your python file.")
	exit(0)

if not exists(sys.argv[1]):
	prRed(f"It appears the file '{sys.argv[1]}' does not exist!")
	exit(0)

with open(sys.argv[1], 'r') as fObj:
	lines = fObj.readlines()

for line in lines:
	if not o1:
		if '.getcwd()' in line:
			o1 = True
	if not o2:
		if '.listdir' in line and '/tmp' in line:
			o2 = True
	if not o3:
		if '.mkdir' in line and 'workdir' in line:
			o3 = True

if not o1:
	prRed("It appears you didn't get the current working directory!")
	exit(0)
if not o2:
	prRed("It appears you didn't list the directory contents of '/tmp'!")
	exit(0)
if not o3:
	prRed("It appears you didn't create the directoy 'workdir' in your current working directory!")
	exit(0)

prGreen("Here is your flag!")
with open('/flag', 'r') as fObj:
    prGreen(fObj.read())
