#!/usr/bin/exec-suid --real -- /usr/bin/python -I
from os.path import exists
import sys

def prRed(skk): print("\033[91m {}\033[00m" .format(skk))
def prGreen(skk): print("\033[92m {}\033[00m" .format(skk))
def prYellow(skk): print("\033[93m {}\033[00m" .format(skk))

i1 = False
i2 = False
i3 = False

if len(sys.argv) != 2:
	prYellow("Please supply the name of your file.\nExample: /challenge/verify <yourpythonfile.py>")
	exit(0)

if not exists(sys.argv[1]):
	prRed("That file doesn't seem to exist.\nPlease give me your python file.")
	exit(0)

with open(sys.argv[1], 'r') as fObj:
	lines = fObj.readlines()

for line in lines:
	if not i1:
		if 'import argparse as ap' in line:
			i1 = True
	if not i2:
		if 'from math import floor' in line:
			i2 = True
	if not i3:
		if 'floor(' in line:
			i3 = True

if not i1:
	prRed("It seems like you didn't use the 'import as' syntax in your code.")
	exit(0)
if not i2:
	prRed("It seems like you didn't use the 'from import' syntax in your code.")
	exit(0)
if not i3:
	prRed("It seems like you didn't use the 'floor' function that you imported!")
	exit(0)

prGreen("Here is your flag!")
with open('/flag', 'r') as fObj:
    prGreen(fObj.read())
