#!/usr/bin/exec-suid --real -- /usr/bin/python -I
from os.path import exists
import sys

s1 = False
s2 = False
s3 = False
s4 = False

def prRed(skk): print("\033[91m {}\033[00m" .format(skk))
def prGreen(skk): print("\033[92m {}\033[00m" .format(skk))
def prYellow(skk): print("\033[93m {}\033[00m" .format(skk))

if len(sys.argv) != 2:
	prRed("Please supply your python file.")
	exit(0)

if not exists(sys.argv[1]):
	prRed(f"It appears the file '{sys.argv[1]}' does not exist!")
	exit(0)

with open(sys.argv[1], 'r') as fObj:
	lines = fObj.readlines()

for line in lines:
	if not s1:
		if 'print' in line and 'sys.argv' in line:
			s1 = True
	if not s2:
		if 'print' in line and 'sys.version' in line:
			s2 = True
	if not s3:
		if 'print' in line and 'sys.path' in line:
			s3 = True
	if not s4:
		if 'sys.exit(0)' in line:
			s4 = True

if not s1:
	prRed("It appears you didn't print out the command line argument!")
	sys.exit(0)
if not s2:
	prRed("It appears you didn't print out the python version information!")
	sys.exit(0)
if not s3:
	prRed("It appears you didn't print out python's path!")
	sys.exit(0)
if not s4:
	prRed("It appears you didn't exit with code 0!")
	sys.exit(0)

prGreen("Here is your flag!")
with open('/flag', 'r') as fObj:
    prGreen(fObj.read())
